### ISSUE TITLE
/apple URL does not work

### ISSUE THREAD

**Issue by joshms123** [wdes/mail-autodiscover-autoconfig#5]
Hello,
When navigating to /apple or /dns-zone, the application just returns 404 not found; however when navigating to mobile config (with email filled in) it downloads the profile.

**Comment by williamdes** [comment]
Hi @joshms123
Indeed, I did not release this yet
I will try to release it today

**Comment by williamdes** [comment]
I deployed this on an edge version:
```sh
docker pull ghcr.io/wdes/mail-autodiscover-autoconfig/mail-autodiscover-autoconfig:edge
```

**Comment by joshms123** [comment]
Hello, I don't seem to have access to that package. Thank you for the help so far.

**Comment by williamdes** [comment]
> I don't seem to have access to that package

You need to use 
```
# docker login ghcr.io
username: joshms123
password: githubPasswordOrUserToken
```

I deployed this on my server and I have a minor UI improvement to do before releasing the final version

**Comment by joshms123** [comment]
I did login and it just displayed access denied. When I navigate to the packages page, it does show the deployment but when I navigate to said deployment it says 0 packages.

**Comment by williamdes** [comment]
> I did login and it just displayed access denied.

Do you mean at the login stage ?
I did create a token at https://github.com/settings/tokens with `read:packages` and used it as a password

**Comment by williamdes** [comment]
Oops: it's `docker login ghcr.io`

**Comment by joshms123** [comment]
Yes; I've also tested by pulling another public GHCR package and that worked.

**Comment by williamdes** [comment]
Here is part of my production docker-compose
```yml
    mail-autodiscover-autoconfig:
        #image: wdes/mail-autodiscover-autoconfig:latest
        image: ghcr.io/wdes/mail-autodiscover-autoconfig/mail-autodiscover-autoconfig:edge
        mem_limit: 120M
        mem_reservation: 50M
        restart: on-failure:40
        network_mode: host
        environment:
            ROCKET_PROFILE: production
            ROCKET_ADDRESS: "2a10:4646:xxx::xxx"
            ROCKET_PORT: "80"
            ROCKET_LOG_LEVEL: normal
            APPLE_MAIL_UUID: ccf622ec-1905-4c60-xxx-4fa1455cbee4
            APPLE_PROFILE_UUID: 1ceeceea-bc41-4131-xxx-f8b13e429cb3
            CUSTOM_DOMAINS: xxx.xxx
            IMAP_HOSTNAME: imap.xxx.xxx.xxx
            POP_HOSTNAME: pop.xxx.xxx.xxx
            SMTP_HOSTNAME: smtp.xxx.xxx.xxx
```

How is yours ?

**Comment by joshms123** [comment]
```yml
services:
  mail-acd:
    image: ghcr.io/wdes/mail-autodiscover-autoconfig/mail-autodiscover-autoconfig:edge
```

**Comment by williamdes** [comment]
Okay I got it, it was private..
Sorry for the mistake
Let me know how the Apple page works out

**Comment by joshms123** [comment]
That now all works. However, seems I've ran into another issue. Even though in the env my IMAP_HOSTNAME is set to a custom server, it seems to default back to imap.domain.tld (only tested in the config-v1.1.xml so far). Would you like me to move this to a new issue?

**Comment by williamdes** [comment]
Did you add it to `CUSTOM_DOMAINS` by mistake ?

**Comment by joshms123** [comment]
My config is as follows:
```yml
      CUSTOM_DOMAINS: domain.tld
      IMAP_HOSTNAME: mail.provider.tld
      POP_HOSTNAME: mail.provider.tld
      SMTP_HOSTNAME: mail.provider.tld
```
However, it seems to come back with imap.domain.tld instead of mail.provider.tld. Also just read through the output of apple xml config and it has the same issue.
