### ISSUE TITLE
Specify server ports

### ISSUE THREAD

**Issue by lekr74** [wdes/mail-autodiscover-autoconfig#7]
Hello,

I deployed your container, and it’s working great for both iOS and thunderbird.
In the meantime I have an issue with outlook (the old way to configure via Control Panel) : 
It does detect that it’s an IMAP server, but fails to configure it properly (port and authentication) for IMAp and SMTP.
So, is there a way to specify ports for both protocols, and that the submission server needs authentication ?
I tried adding port to the server details on the compose file, but it doesn’t seems to change anything
Here's my compose file : 

```yaml
version: "3"
services:
  mail-autodiscover-autoconfig:
    image: wdes/mail-autodiscover-autoconfig:latest
    mem_limit: 120M
    mem_reservation: 50M
    restart: on-failure:40
    ports:
      - 8088:80
    environment:
      ROCKET_PROFILE: production
      ROCKET_ADDRESS: 0.0.0.0
      ROCKET_PORT: "80"
      # https://www.uuidgenerator.net/
      # Re-generate the two UUIDs below
      APPLE_MAIL_UUID: 6761f511-ffd8-4c01-bf1e-1563182044ca
      APPLE_PROFILE_UUID: 856ac4fe-af7f-4290-802f-975e9df962fa
      # CUSTOM_DOMAINS: foo.tld
      # (optional: CUSTOM_DOMAINS) List of domains that will use {imap,pop,smtp}.domain.tld instead of the hosts below
      IMAP_HOSTNAME: mail.domain.fr:993
      POP_HOSTNAME: mail.domain.fr
      SMTP_HOSTNAME: mail.domain.fr:465
networks: {}

```

Thanks in advance
